CREATE TABLE complex AS 
SELECT   C.C_CUSTKEY                                                        AS C_CUSTKEY, 
         CONCAT('"', CAST (C.C_NAME AS    VARCHAR), '"')                    AS C_NAME, 
         CONCAT('"', CAST (C.C_ADDRESS AS VARCHAR), '"')                    AS C_ADDRESS, 
         C.C_NATIONKEY                                                      AS C_NATIONKEY, 
         CONCAT('"', CAST (C.C_PHONE AS VARCHAR), '"')                      AS C_PHONE, 
         C.C_ACCTBAL                                                        AS C_ACCTBAL, 
         CONCAT('"', CAST (C.C_MKTSEGMENT AS VARCHAR), '"')                 AS C_MKTSEGMENT, 
         CONCAT('"', CAST (C.C_COMMENT AS    VARCHAR), '"')                 AS C_COMMENT, 
         O.O_ORDERKEY                                                       AS O_ORDERKEY, 
         CONCAT('"', CAST (O.O_ORDERSTATUS AS VARCHAR), '"')                AS O_ORDERSTATUS , 
         O.O_TOTALPRICE                                                     AS O_TOTALPRICE, 
         CONCAT('"', CAST (O.O_ORDERDATE AS     VARCHAR), '"')              AS O_ORDERDATE, 
         CONCAT('"', CAST (O.O_ORDERPRIORITY AS VARCHAR), '"')              AS O_ORDERPRIORITY, 
         CONCAT('"', CAST (O.O_CLERK AS         VARCHAR), '"')              AS O_CLERK, 
         O.O_SHIPPRIORITY                                                   AS O_SHIPPRIORITY, 
         CONCAT('"', CAST (O.O_COMMENT AS VARCHAR), '"')                    AS O_COMMENT, 
         L.L_PARTKEY                                                        AS L_PARTKEY, 
         L.L_SUPPKEY                                                        AS L_SUPPKEY, 
         L.L_LINENUMBER                                                     AS L_LINENUMBER, 
         L.L_QUANTITY                                                       AS L_QUANTITY, 
         L.L_EXTENDEDPRICE                                                  AS L_EXTENDEDPRICE, 
         L.L_DISCOUNT                                                       AS L_DISCOUNT, 
         L.L_TAX                                                            AS L_TAX, 
         CONCAT('"', CAST (L.L_RETURNFLAG AS   VARCHAR), '"')               AS L_RETURNFLAG, 
         CONCAT('"', CAST (L.L_LINESTATUS AS   VARCHAR), '"')               AS L_LINESTATUS, 
         CONCAT('"', CAST (L.L_SHIPDATE AS     VARCHAR), '"')               AS L_SHIPDATE, 
         CONCAT('"', CAST (L.L_COMMITDATE AS   VARCHAR), '"')               AS L_COMMITDATE, 
         CONCAT('"', CAST (L.L_RECEIPTDATE AS  VARCHAR), '"')               AS L_RECEIPTDATE , 
         CONCAT('"', CAST (L.L_SHIPINSTRUCT AS VARCHAR), '"')               AS L_SHIPINSTRUCT,
         CONCAT('"', CAST (L.L_SHIPMODE AS     VARCHAR), '"')               AS L_SHIPMODE, 
         CONCAT('"', CAST (L.L_COMMENT AS      VARCHAR), '"')               AS L_COMMENT 
FROM     customer C, 
         orders O, 
         lineitem L 
WHERE    C.C_CUSTKEY = O.O_CUSTKEY 
AND      O.O_ORDERKEY = L.L_ORDERKEY 
ORDER BY C.C_CUSTKEY, 
         O.O_ORDERKEY
